<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
		xmlns:services="http://localhost:8080/blue-config/ns/services"
		xmlns:hosts="http://localhost:8080/blue-config/ns/hosts"
		xmlns:servicegroups="http://localhost:8080/blue-config/ns/servicegroups"
		xmlns:hostgroups="http://localhost:8080/blue-config/ns/hostgroups"
		xmlns:contacts="http://localhost:8080/blue-config/ns/contacts"
		xmlns:contactgroups="http://localhost:8080/blue-config/ns/contactgroups"
		xmlns:timeperiods="http://localhost:8080/blue-config/ns/timeperiods"
		xmlns:commands="http://localhost:8080/blue-config/ns/commands"
		xmlns:servicedependencies="http://localhost:8080/blue-config/ns/servicedependency"
		xmlns:serviceescalations="http://localhost:8080/blue-config/ns/serviceescalation"
		xmlns:hostdependencies="http://localhost:8080/blue-config/ns/hostdependency"
		xmlns:hostescalations="http://localhost:8080/blue-config/ns/hostescalation"
		xmlns:hostextinfos="http://localhost:8080/blue-config/ns/hostextinfo"
		xmlns:serviceextinfos="http://localhost:8080/blue-config/ns/serviceextinfo"
		xmlns:macros="http://localhost:8080/blue-config/ns/macros.xsd">
 	<xsl:output method="text"/>	
 	
 	<xsl:template match="/">
<xsl:text>
#############################################################################################
# This file is automatically generated by the Blue framework. Please be careful when editing#
# this file by hand as any mistakes may cause unexpected behaviour in your monitoring setup.#
#############################################################################################
</xsl:text> 	 	
 	 	<xsl:apply-templates select="services:services"/>
 	 	<xsl:apply-templates select="servicegroups:servicegroups"/>
 	 	<xsl:apply-templates select="hosts:hosts"/>
 	 	<xsl:apply-templates select="hostgroups:hostgroups"/>
 	 	<xsl:apply-templates select="contacts:contacts"/>
 	 	<xsl:apply-templates select="contactgroups:contactgroups"/>
 	 	<xsl:apply-templates select="timeperiods:timeperiods"/>
 	 	<xsl:apply-templates select="commands:commands"/>
 	 	<xsl:apply-templates select="servicedependencies:servicedependencies"/>
 	 	<xsl:apply-templates select="serviceescalations:serviceescalations"/>
 	 	<xsl:apply-templates select="hostdependencies:hostdependencies"/>
 	 	<xsl:apply-templates select="hostescalations:hostescalations"/>
 	 	<xsl:apply-templates select="hostextinfos:hostextinfos"/>
 	 	<xsl:apply-templates select="serviceextinfos:serviceextinfos"/>
<xsl:text>#EOF</xsl:text>
 	</xsl:template>
 	
 	<xsl:template match="services:service">
define service{
	<xsl:for-each select="*">
 	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
 	<xsl:text>
 	</xsl:text>
 	</xsl:for-each>
}
 	</xsl:template>
 	
 	<xsl:template match="servicegroups:servicegroup">
 define servicegroup{
 	servicegroup_name 		<xsl:value-of select="servicegroups:servicegroup_name"/>
 	alias 		        	<xsl:value-of select="servicegroups:alias"/>
 	members 	 	        <xsl:value-of select="servicegroups:members"/>
 } 	
 	</xsl:template>
 	
 	<xsl:template match="hosts:host">
define host{
 	<xsl:for-each select="*">
 	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
 	<xsl:text>
 	</xsl:text>
 	</xsl:for-each>
}
 	</xsl:template>
 	
 	<xsl:template match="hostgroups:hostgroup">
 define hostgroup{
 	hostgroup_name			<xsl:value-of select="hostgroups:hostgroup_name"/>
 	alias	       			<xsl:value-of select="hostgroups:alias"/>
 	members	       			<xsl:value-of select="hostgroups:members"/>
 }		
 	</xsl:template>

	<xsl:template match="contacts:contact">
define contact{
	<xsl:for-each select="*">
	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
	<xsl:text>
	</xsl:text>
	</xsl:for-each>
}
	</xsl:template>
	
	<xsl:template match="contactgroups:contactgroup">
define contactgroup{
	contactgroup_name		<xsl:value-of select="contactgroups:contactgroup_name"/>
	alias		  		<xsl:value-of select="contactgroups:alias"/>
	members		  		<xsl:value-of select="contactgroups:members"/>
}
	</xsl:template>
	
	<xsl:template match="timeperiods:timeperiod">
define timeperiod{
	<xsl:for-each select="*">
	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
	<xsl:text>
	</xsl:text>
	</xsl:for-each>
}
	</xsl:template>
  	 	
  	 <xsl:template match="commands:command">
define command{
	command_name		<xsl:value-of select="commands:command_name"/>
	command_line		<xsl:value-of select="commands:command_line"/>
}  	 
  	 </xsl:template>
  	 
  	 <xsl:template match="servicedependencies:servicedependency">
define servicedependency{
	 <xsl:for-each select="*">
	 <xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
	 <xsl:text>
	 </xsl:text>
	 </xsl:for-each>
}  	 
  	 </xsl:template>
  	 
  	 <xsl:template match="serviceescalations:serviceescalation">
define serviceescalation{
  	 <xsl:for-each select="*">
  	 <xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
  	 <xsl:text>
  	 </xsl:text>
  	 </xsl:for-each>
}
  	 </xsl:template>
  	 
  	 <xsl:template match="hostdependencies:hostdependency">
define hostdependency{
	<xsl:for-each select="*">
	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
	<xsl:text>
	</xsl:text>
	</xsl:for-each>	
}
  	 </xsl:template>
  	 
  	 <xsl:template match="hostescalations:hostescalation">
define hostescalation{
  	 <xsl:for-each select="*">
  	 <xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
  	 <xsl:text>
  	 </xsl:text>
  	 </xsl:for-each>
}
  	 </xsl:template>

	<xsl:template match="hostextinfos:hostextinfo">
define hostextinfo{
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:host_name">
		<xsl:text>host_name		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:host_name"/> <xsl:text>
		</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:notes">
		<xsl:text>notes			</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:notes"/> <xsl:text>
		</xsl:text>			
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:notes_url">
		<xsl:text>notes_url		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:notes_url"/> <xsl:text>
		</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:action_url">
		<xsl:text>action_url		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:action_url"/> <xsl:text>
		</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:icon_image">
		<xsl:text>icon_image		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:icon_image"/> <xsl:text>
		</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:icon_image_alt">
		<xsl:text>icon_image_alt		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:icon_image_alt"/> <xsl:text>
			</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:vrml_image">
		<xsl:text>vrml_image		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:vrml_image"/> <xsl:text>
			</xsl:text>
			</xsl:if>
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:statusmap_image">
		<xsl:text>statusmap_image 	</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:statusmap_image"/> <xsl:text>
		</xsl:text>
			</xsl:if>			
			
			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:twod_coords">
		<xsl:text>2d_coords		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:twod_coords"/> <xsl:text>
		</xsl:text>
			</xsl:if>

			<xsl:if test="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:threed_coords">
		<xsl:text>3d_coords		</xsl:text> <xsl:value-of select="/hostextinfos:hostextinfos/hostextinfos:hostextinfo/hostextinfos:threed_coords"/><xsl:text>
		</xsl:text>
			</xsl:if>
}
	</xsl:template>

	<xsl:template match="serviceextinfos:serviceextinfo">
define serviceextinfo{
	<xsl:for-each select="*">
	<xsl:value-of select="local-name()"/><xsl:text>		</xsl:text><xsl:value-of select="."/>
	<xsl:text>
	</xsl:text>
	</xsl:for-each>
}
  	 </xsl:template>
  	
</xsl:stylesheet>